export const words = {
	"Animals": ["DOG","CAT"],
	"Food":["PIZZA","CHICKEN","CORNED BEEF","EGGS BENEDICT","MACARONI AND CHEESE","ONION RING","PASTA SALAD","POTATO WEDGES","STEAK SANDWICH","WAFFLE",],
	"Farm_Animals":["PIG","COW","DOG","CAT","GOAT","CHICKEN","DUCK","HORSE","SHEEP","RABBIT"],
	"Famous_People":["NIGHTINGALE","GHANDI","WASHINGTON","EINSTEIN","LINCOLN","PRESLEY","DA VINICI","SHAKESPEARE","HAWKING","NAPOLEON"],
	"Capital_Cities":["LONDON","PARIS","ROME","BERLIN","SEOUL","WASHINGTON DC","TOKYO","MADRID","NEW DELHI","BEIJING"],
	"Engineering":["NUTS","BOLTS","SPANNER","SCREW DRIVER","SAW","PLIERS","SCREW","METAL"]
}